{% set name = "imaxt-multiscale-plugin" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imaxt-multiscale-plugin-{{ version }}.tar.gz
  sha256: e3ba818ad9d665f3a2a1999b01772137675046a7afd4faf5fc255ca064e883e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - astropy
    - dask-core
    - imageio
    - imaxt-image
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - xarray
    - zarr

test:
  imports:
    - imaxt_multiscale_plugin
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://gitlab.developers.cam.ac.uk/astronomy/camcead/imaxt/imaxt-multiscale-plugin
  summary: A simple plugin to use with napari
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eddienko
    - goanpeca
    - jaimergp
