{% set name = "imaxt-multiscale-plugin" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imaxt-multiscale-plugin-{{ version }}.tar.gz
  sha256: f544a5a2978ef9b2c6c01aa5c978bb80854a3c47b24f9ddb426033028fe460ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - dask-core
    - imaxt-image
    - magicgui
    - napari
    - numpy
    - python >=3.8
    - qtpy
    - xarray

test:
  imports:
    - imaxt_multiscale_plugin
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://gitlab.developers.cam.ac.uk/astronomy/camcead/imaxt/imaxt-multiscale-plugin
  summary: A simple plugin to use with napari
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eddienko
    - goanpeca
    - jaimergp
